name: Readme CI
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  docs:
    name: Update README
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Update README
        run: node generate-readme.mjs

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: Update graphs in README"
